[local]
localhost 

# ansible_python_interpreter=/usr/bin/python3.9
[mongodb]
localhost

[redis]
localhost

[mysql]
localhost

[rabbitmq]
localhost

[catalogue]
localhost

[cart]
localhost

[user]
localhost

[shipping]
localhost

[payment]
localhost

[frontend]
localhost