[local]
localhost 

# ansible_python_interpreter=/usr/bin/python3.9
[mongodb]
localhost

[redis]
localhost

[mysql]
localhost

[rabbitmq]
localhost

[catalogue]
catalogue.vijayaws.fun

[cart]
cart.vijayaws.fun

[user]
user.vijayaws.fun

[shipping]
shipping.vijayaws.fun

[payment]
payment.vijayaws.fun

[frontend]
frontend.vijayaws.fun